name: Build

on:
  push:
    branches: [ jenkins-main ]
  pull_request:
    branches: [ jenkins-main ]

jobs:
  war:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Maven Build
      run: mvn -am -pl war,bom -Pquick-build clean install
    - uses: actions/upload-artifact@v4
      with:
        name: jenkins.war
        path: ./war/target/jenkins.war
        if-no-files-found: error

  docker-image:
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    runs-on: ubuntu-latest
    needs: war
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: jenkins.war
        path: ./docker/target
    - name: Docker Login
      run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
    - name: Debug data
      run: echo pwd; pwd; echo ls; ls -la; echo tree docker/target; tree ./docker/target; true
    - name: Docker Build
      run: docker build -t vladaionescu/test:jenkins -f ./docker/21/debian/bookworm/hotspot/Dockerfile ./docker
    - name: Docker Push
      run: docker push vladaionescu/test:jenkins
